import fs from 'node:fs';
import { createHash } from 'node:crypto';

(async function main(retries = 4) {
  if (retries < 0) {
    throw new Error('Failed to fetch media types');
  }

  try {
    const response = await fetch(
      'https://www.iana.org/assignments/media-types/media-types.xml',
      {
        redirect: 'follow',
      },
    );
    const { ok, status, statusText } = response;
    if (!ok) {
      throw new Error(`HTTP ${status} ${statusText}`);
    }

    const textData = await response.text();
    const dom =
      typeof DOMParser === 'undefined'
        ? new (await import('jsdom')).JSDOM(textData).window.document
        : new DOMParser().parseFromString(textData, 'application/xml');

    const mediaTypes = Array.from(
      new Set(
        (function* () {
          for (const registry of dom.querySelectorAll(
            '#media-types registry',
          )) {
            const title = registry.querySelector('title')?.textContent;
            if (!title) {
              continue;
            }
            for (const record of registry.getElementsByTagName('record')) {
              yield record.querySelector('file[type=template]')?.textContent ??
                `${title}/${record.querySelector('name').textContent}`;
            }
          }
        })(),
      ),
    ).sort();

    const output = JSON.stringify(mediaTypes, undefined, 2);
    const hash = createHash('sha256');
    hash.update(output);
    hash.update('\n');
    fs.writeFileSync('index.json', output + '\n');
    fs.writeFileSync(
      'index.js',
      `\
// @generated by build.js
export const updated = new Date('${new Date().toISOString()}');
export const lastModified = '${response.headers.get('last-modified')}';
export const hash =
  '${hash.digest('hex')}';

export default ${output};
`,
    );
  } catch (error) {
    console.error(error);
    console.warn(`There are ${retries} retries left...\n`);
    main(--retries);
  }
})();
